// <auto-generated />
using E_Commerce_Sv.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_Sv.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230609154705_CreatingAndSeedingCategoryTable")]
    partial class CreatingAndSeedingCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Sv.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Graphic Cards that will suit ur needs in every aspect!",
                            Name = "Graphic Cards"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Best of gaming desktops on market",
                            Name = "Gaming Desktops"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The fastest laptops on market",
                            Name = "Laptops"
                        });
                });

            modelBuilder.Entity("E_Commerce_Sv.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Desktop",
                            CategoryId = 1,
                            Description = "graficka komponenta",
                            Name = "AMD Radeon RX 580",
                            Price = 150
                        },
                        new
                        {
                            Id = 2,
                            Category = "Desktop",
                            CategoryId = 1,
                            Description = "graficka komponenta",
                            Name = "NVIDIA GEFORCE GTX",
                            Price = 250
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
